wandb_version: 1

Model:
  desc: null
  value: LayoutLMv3
Weights:
  desc: null
  value: microsoft/layoutlmv3-base
Dataset:
  desc: null
  value: infographicVQA
Page retrieval:
  desc: null
  value: None
Visual Encoder:
  desc: null
  value: '-'
Batch size:
  desc: null
  value: 20
Max. Seq. Length:
  desc: null
  value: '-'
lr:
  desc: null
  value: 1e-4
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710269196.172168
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
