save_dir: saving_dir/
model_name: hy
# model_weights: rubentito/layoutlmv3-base-mpdocvqa
model_weights: microsoft/layoutlmv3-base
# model_weights: /home/ges/level3-cv-productserving-cv-10/MP-DocVQA-Framework-master/saved_dir/checkpoints/layoutlmv3_none_sp-docvqa/model__0.ckpt
device: cuda
data_parallel: False

training_parameters:
  lr: 1e-4
  batch_size: 20
  train_epochs: 55
  # warmup_iterations: 1000
  warmup_iterations: 1
