wandb_version: 1

Model:
  desc: null
  value: hy
Weights:
  desc: null
  value: microsoft/layoutlmv3-base
Dataset:
  desc: null
  value: infographicVQA
Visual Encoder:
  desc: null
  value: '-'
Batch size:
  desc: null
  value: 20
Max. Seq. Length:
  desc: null
  value: null
lr:
  desc: null
  value: 0.0001
seed:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710324663.207819
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.11.7
      5: 0.16.3
      6: 4.38.2
      8:
      - 1
      - 5
      13: linux-x86_64
Model Params:
  desc: null
  value: 125
Model Trainable Params:
  desc: null
  value: 125
Best Accuracy:
  desc: null
  value: 0.03125
Best epoch:
  desc: null
  value: 0
